apiVersion: v1
kind: Service
metadata:
    name: partida
    labels:
        name: partida
spec:
    type: NodePort
    ports:
        - port: 8080
          targetPort: 8080
          protocol: TCP
    selector:
        app: partida